# Generated by Django 5.1.7 on 2025-03-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='invoice_id',
            new_name='facture_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='observation',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='pfe.client'),
        ),
        migrations.AlterField(
            model_name='case',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='pfe.user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='pfe.region'),
        ),
        migrations.AlterField(
            model_name='datechange',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='pfe.case'),
        ),
        migrations.AlterField(
            model_name='etat',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='pfe.case'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='pfe.client'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Boufarik', 'Boufarik'), ('Mouzaia', 'Mouzaia'), ('Larbaa', 'Larbaa'), ('OuladYaich', 'Oulad Yaich'), ('ElWouroud', 'El Wouroud'), ('Bougara', 'Bougara'), ('Afroun', 'Afroun')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ResponsableDeBoufarik', 'Responsable de Boufarik'), ('ResponsableDeMouzaia', 'Responsable de Mouzaia'), ('ResponsableDeLarbaa', 'Responsable de Larbaa'), ('ResponsableDeOuladYaich', 'Responsable de Oulad Yaich'), ('ResponsableDeElWouroud', 'Responsable de El Wouroud'), ('ResponsableDeBougara', 'Responsable de Bougara'), ('ResponsableDeAfroun', 'Responsable de Afroun')], max_length=30),
        ),
    ]
