# Generated by Django 5.1.7 on 2025-03-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_delete_total_rename_invoice_id_facture_facture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
